{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "producer-service.serviceAccountName" . }}
  labels:
{{ include "producer-service.labels" . | nindent 4 }}
{{- end -}}
