apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracing.fullname" . }}
  labels:
    {{- include "tracing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: zipkin
      protocol: TCP
      name: zipkin
  selector:
    {{- include "tracing.selectorLabels" . | nindent 4 }}