info:
  name: ${spring.application.name}

server:
  port: 8080

client:
  word:
    name: word
    connectTimeout: 1000
    readTimeout: 1000

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: false
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.lang.Throwable
  instances:
    word:
      baseConfig: default

logging:
  level:
    root: info